name: crib_x
description: "cribx"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  firebase_messaging: ^16.7.0
  get: ^4.7.3
  dio: ^5.11.1
  image_picker: ^1.2.3
  connectivity_plus: ^7.3.1
  flutter_secure_storage: ^11.2.0
  google_fonts: ^9.0.0
  flutter_svg: ^2.3.0
  cached_network_image: ^4.0.4
  shimmer: ^4.0.0
  flutter_dotenv: ^6.0.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8
  intl: ^0.20.3
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.png"
  adaptive_icon_background: "#1F1F1F"
  adaptive_icon_foreground: "assets/images/icons/app_icon_foreground.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logos/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logos/logo_light.png
  color_dark: "#1F1F1F"
  image_dark: assets/images/logos/logo_dark.png

  android_gravity: center
  ios_content_mode: center

  android_12:
    color: "#FFFFFF"
    image: assets/images/logos/logo_android12_light.png
    color_dark: "#1F1F1F"
    image_dark: assets/images/logos/logo_android12_dark.png

  fullscreen: true